name: release to cargo

on:
  push:
    tags: ["v*"]

jobs:
  validate-release-tag:
    name: Validate git tag
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: compare git tag with cargo metadata
        run: |
          PUSHED_TAG=${GITHUB_REF##*/}
          CURR_VER=$( grep version Cargo.toml | head -n 1 | awk '{print $3}' | tr -d '"' )
          if [[ "${PUSHED_TAG}" != "v${CURR_VER}" ]]; then
            echo "Cargo metadata has version set to ${CURR_VER}, but got pushed tag ${PUSHED_TAG}."
            exit 1
          fi

  # release-crate:
  #   needs: validate-release-tag
  #   name: Release crate
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true

  #     - name: install protoc
  #       uses: arduino/setup-protoc@v2
  #       with:
  #         version: 23.x

  #     - name: cargo publish core
  #       uses: actions-rs/cargo@v1
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #       with:
  #         command: publish
  #         args: --token "${CARGO_REGISTRY_TOKEN}" --package spark-connect-core --manifest-path ./Cargo.toml

  #     - name: cargo publish rust
  #       uses: actions-rs/cargo@v1
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  #       with:
  #         command: publish
  #         args: --token "${CARGO_REGISTRY_TOKEN}" --package spark-connect-rs --manifest-path ./Cargo.toml
